// transcripts.test.ts — peer of transcripts.ts: the user's own turns from Claude
// Code's and Codex's session files, what is dropped, which record wins, and that
// corrections.ts hands a non-T3 session to it.
//
// Run: node --test --experimental-strip-types .agents/skills/close/scripts/transcripts.test.ts
//
// A throwaway HOME, Claude config dir and Codex home; no T3 database; TZ pinned
// to UTC; every harness session variable absent unless a case sets one. The
// cases run in order and share the fixtures.

import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, realpathSync, rmSync, utimesSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { after, test } from "node:test";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SUT = join(HERE, "transcripts.ts");
const TMP = realpathSync(mkdtempSync(join(tmpdir(), "transcripts-test-")));
after(() => rmSync(TMP, { recursive: true, force: true }));

const CLAUDE = join(TMP, "claude");
const CODEX = join(TMP, "codex");
const BASE: Record<string, string> = {
  PATH: process.env.PATH ?? "",
  TZ: "UTC",
  HOME: join(TMP, "home"),
  T3CODE_HOME: join(TMP, "no-t3"),
  CLAUDE_CONFIG_DIR: CLAUDE,
  CODEX_HOME: CODEX,
};
mkdirSync(BASE.HOME as string, { recursive: true });

const W = join(TMP, "shop");
spawnSync("git", ["init", "-q", W]);

function run(args: string[] = [], env: Record<string, string> = {}, script = SUT): { rc: number | null; out: string; err: string } {
  const r = spawnSync(process.execPath, ["--no-warnings", "--experimental-strip-types", script, ...args], {
    cwd: W,
    encoding: "utf8",
    env: { ...BASE, ...env },
  });
  return { rc: r.status, out: r.stdout.replace(/\n+$/, ""), err: r.stderr };
}

test("no record anywhere: exit 2, and says so", () => {
  const r = run();
  assert.equal(r.rc, 2);
  assert.ok(r.err.includes("no record of this session"), r.err);
});

// ── Claude Code ──────────────────────────────────────────────────────────

const CLAUDE_SESSION = [
  { type: "user", timestamp: "2026-01-12T09:00:00.000Z", message: { role: "user", content: "Add a retry to checkout." } },
  {
    type: "assistant",
    timestamp: "2026-01-12T09:00:05.000Z",
    message: { role: "assistant", content: [{ type: "text", text: "On it." }] },
  },
  {
    type: "user",
    timestamp: "2026-01-12T09:01:00.000Z",
    message: { role: "user", content: [{ type: "tool_result", tool_use_id: "t1", content: "exit 0" }] },
  },
  {
    type: "user",
    timestamp: "2026-01-12T09:02:00.000Z",
    isMeta: true,
    message: { role: "user", content: "Caveat: The messages below were generated by the user while running local commands." },
  },
  {
    type: "user",
    timestamp: "2026-01-12T09:03:00.000Z",
    message: {
      role: "user",
      content: [
        {
          type: "text",
          text: "<system-reminder>be careful</system-reminder>No, retry once, not three times.\nThe processor bills each attempt.",
        },
      ],
    },
  },
  { type: "user", timestamp: "2026-01-12T09:04:00.000Z", message: { role: "user", content: "/close" } },
  {
    type: "user",
    timestamp: "2026-01-12T09:04:30.000Z",
    message: { role: "user", content: "/close but first say why the push failed" },
  },
  {
    type: "user",
    timestamp: "2026-01-12T09:05:00.000Z",
    message: {
      role: "user",
      content: [
        { type: "tool_result", tool_use_id: "t2", content: 'User has answered your questions: "Which store?"="Postgres"' },
      ],
    },
  },
  {
    type: "user",
    timestamp: "2026-01-12T09:06:00.000Z",
    isSidechain: true,
    message: { role: "user", content: "a subagent prompt" },
  },
];
const jsonl = (rows: unknown[]): string => `${rows.map((r) => JSON.stringify(r)).join("\n")}\n`;

test("claude: typed turns, reminders stripped, invocations and tool output dropped", () => {
  const dir = join(CLAUDE, "projects", W.replace(/[^A-Za-z0-9]/g, "-"));
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "sess-1.jsonl"), jsonl(CLAUDE_SESSION));
  const r = run();
  assert.equal(
    r.out,
    [
      "09:00\tAdd a retry to checkout.",
      "09:03\tNo, retry once, not three times.",
      "09:04\t/close but first say why the push failed",
      '09:05\t[answered] "Which store?"="Postgres"',
    ].join("\n"),
  );
  assert.ok(r.err.includes("source claude"), "…names its source");
  assert.equal(
    run(["--full"]).out.split("\n")[1],
    "09:03\tNo, retry once, not three times.\\nThe processor bills each attempt.",
    "--full keeps the whole turn, newlines escaped",
  );
});

test("claude: the session id picks the transcript", () => {
  mkdirSync(join(CLAUDE, "projects/-elsewhere"), { recursive: true });
  writeFileSync(
    join(CLAUDE, "projects/-elsewhere/abc-123.jsonl"),
    jsonl([{ type: "user", timestamp: "2026-01-12T10:00:00.000Z", message: { role: "user", content: "from the id" } }]),
  );
  assert.equal(run([], { CLAUDE_CODE_SESSION_ID: "abc-123" }).out, "10:00\tfrom the id");
});

// ── Codex ────────────────────────────────────────────────────────────────

const ROLL = join(CODEX, "sessions/2026/01/12");

test("codex beats a claude transcript found only by directory; --source and a Claude id override", () => {
  mkdirSync(ROLL, { recursive: true });
  writeFileSync(
    join(ROLL, "rollout-a.jsonl"),
    jsonl([
      { timestamp: "2026-01-12T11:00:00.000Z", type: "session_meta", payload: { id: "x", cwd: W } },
      {
        timestamp: "2026-01-12T11:00:01.000Z",
        type: "response_item",
        payload: {
          type: "message",
          role: "user",
          content: [{ type: "input_text", text: "# AGENTS.md instructions\n\n<INSTRUCTIONS>rules</INSTRUCTIONS>" }],
        },
      },
      {
        timestamp: "2026-01-12T11:00:02.000Z",
        type: "response_item",
        payload: { type: "message", role: "user", content: [{ type: "input_text", text: "Ship the sync engine." }] },
      },
      {
        timestamp: "2026-01-12T11:00:02.000Z",
        type: "event_msg",
        payload: { type: "user_message", message: "Ship the sync engine." },
      },
      {
        timestamp: "2026-01-12T11:05:00.000Z",
        type: "event_msg",
        payload: {
          type: "item_completed",
          item: { type: "UserMessage", content: [{ type: "text", text: "That is the wrong table." }] },
        },
      },
    ]),
  );
  writeFileSync(
    join(ROLL, "rollout-b.jsonl"),
    jsonl([
      { timestamp: "2026-01-12T12:00:00.000Z", type: "session_meta", payload: { id: "y", cwd: "/some/other/repo" } },
      { timestamp: "2026-01-12T12:00:02.000Z", type: "event_msg", payload: { type: "user_message", message: "not this session" } },
    ]),
  );
  assert.equal(run().out, "11:00\tShip the sync engine.\n11:05\tThat is the wrong table.");
  assert.equal(run(["--source", "claude"]).out.split("\n")[0], "09:00\tAdd a retry to checkout.", "--source claude forces the other record");
  assert.equal(run([], { CLAUDE_CODE_SESSION_ID: "abc-123" }).out, "10:00\tfrom the id", "…but a Claude session id wins over codex");
});

test("codex: the newest matching rollout; the session's own id picks its rollout", () => {
  const c = join(ROLL, "rollout-c.jsonl");
  writeFileSync(
    c,
    jsonl([
      { timestamp: "2026-01-12T13:00:00.000Z", type: "session_meta", payload: { id: "z", cwd: W } },
      {
        timestamp: "2026-01-12T13:00:01.000Z",
        type: "response_item",
        payload: { type: "message", role: "user", content: [{ type: "input_text", text: "<environment_context>cwd</environment_context>" }] },
      },
      {
        timestamp: "2026-01-12T13:00:02.000Z",
        type: "response_item",
        payload: { type: "message", role: "user", content: [{ type: "input_text", text: "Older format, no events." }] },
      },
    ]),
  );
  // Newer than rollout-a by a clear margin, without sleeping.
  const later = new Date(Date.now() + 5_000);
  utimesSync(c, later, later);
  assert.equal(run().out, "13:00\tOlder format, no events.", "the newest matching rollout, older format read from response items");
  assert.equal(
    run([], { CODEX_THREAD_ID: "x" }).out,
    "11:00\tShip the sync engine.\n11:05\tThat is the wrong table.",
    "the session's own id picks its rollout over a newer one in the same tree",
  );
  assert.equal(
    run([], { CODEX_SESSION_ID: "x" }).out,
    "11:00\tShip the sync engine.\n11:05\tThat is the wrong table.",
    "…CODEX_SESSION_ID too",
  );
});

test("an explicit id with no record fails, for either harness", () => {
  const cx = run([], { CODEX_THREAD_ID: "no-such-session" });
  assert.equal(cx.rc, 2, "codex: an id with no record fails, rather than reading another session's");
  assert.equal(cx.out, "", "…printing nothing");
  const cl = run([], { CLAUDE_CODE_SESSION_ID: "no-such-session" });
  assert.equal(cl.rc, 2, "claude: an id with no record fails, rather than reading the newest transcript");
  assert.equal(cl.out, "", "…printing nothing");
});

// ── corrections.ts hands a session T3 does not know to this script ───────

test("corrections.ts outside T3 reads the harness transcript, --full passed through", () => {
  const corrections = join(HERE, "corrections.ts");
  assert.equal(run([], {}, corrections).out, "13:00\tOlder format, no events.");
  assert.equal(run(["--full"], {}, corrections).out, "13:00\tOlder format, no events.", "…and passes --full through");
});

test("a bad source: usage", () => {
  assert.equal(run(["--source", "nope"]).rc, 2);
});
