#!/usr/bin/env bash
# shellcheck disable=SC2016  # fixtures are literal JSON and markdown
# transcripts.test.sh — peer of transcripts.sh: the user's own turns from Claude
# Code's and Codex's session files, what is dropped, which record wins, and that
# corrections.sh hands a non-T3 session to it. Run: bash transcripts.test.sh
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUT="$HERE/transcripts.sh"
TMP="$(mktemp -d)"; TMP="$(cd "$TMP" && pwd -P)"; trap 'rm -rf "$TMP"' EXIT
unset CLAUDE_CODE_SESSION_ID CLAUDE_SESSION_ID CONTEXTIUM_SESSION CODEX_THREAD_ID CODEX_SESSION_ID
export TZ=UTC HOME="$TMP/home" T3CODE_HOME="$TMP/no-t3" CLAUDE_CONFIG_DIR="$TMP/claude" CODEX_HOME="$TMP/codex"
mkdir -p "$HOME"
pass=0; fail=0
is() { if [[ "$2" == "$3" ]]; then pass=$((pass + 1)); else fail=$((fail + 1)); echo "FAIL: $1"; echo "  expected: [$3]"; echo "  actual:   [$2]"; fi; }
run() { OUT="$(cd "$W" && env "$@" bash "$SUT" 2>"$TMP/err")"; RC=$?; }
runf() { OUT="$(cd "$W" && bash "$SUT" "$@" 2>"$TMP/err")"; RC=$?; }

git init -q "$TMP/shop"; W="$TMP/shop"
run
is "no record anywhere: exit 2" "$RC" "2"
is "…and says so" "$(grep -c 'no record of this session' "$TMP/err")" "1"

# ── Claude Code ──────────────────────────────────────────────────────────
SLUG="$(printf '%s' "$W" | sed 's/[^A-Za-z0-9]/-/g')"
mkdir -p "$CLAUDE_CONFIG_DIR/projects/$SLUG"
cat >"$CLAUDE_CONFIG_DIR/projects/$SLUG/sess-1.jsonl" <<'JSONL'
{"type":"user","timestamp":"2026-01-12T09:00:00.000Z","message":{"role":"user","content":"Add a retry to checkout."}}
{"type":"assistant","timestamp":"2026-01-12T09:00:05.000Z","message":{"role":"assistant","content":[{"type":"text","text":"On it."}]}}
{"type":"user","timestamp":"2026-01-12T09:01:00.000Z","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"t1","content":"exit 0"}]}}
{"type":"user","timestamp":"2026-01-12T09:02:00.000Z","isMeta":true,"message":{"role":"user","content":"Caveat: The messages below were generated by the user while running local commands."}}
{"type":"user","timestamp":"2026-01-12T09:03:00.000Z","message":{"role":"user","content":[{"type":"text","text":"<system-reminder>be careful</system-reminder>No, retry once, not three times.\nThe processor bills each attempt."}]}}
{"type":"user","timestamp":"2026-01-12T09:04:00.000Z","message":{"role":"user","content":"/close"}}
{"type":"user","timestamp":"2026-01-12T09:04:30.000Z","message":{"role":"user","content":"/close but first say why the push failed"}}
{"type":"user","timestamp":"2026-01-12T09:05:00.000Z","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"t2","content":"User has answered your questions: \"Which store?\"=\"Postgres\""}]}}
{"type":"user","timestamp":"2026-01-12T09:06:00.000Z","isSidechain":true,"message":{"role":"user","content":"a subagent prompt"}}
JSONL
run
is "claude: typed turns, reminders stripped, invocations and tool output dropped" "$OUT" "09:00	Add a retry to checkout.
09:03	No, retry once, not three times.
09:04	/close but first say why the push failed
09:05	[answered] \"Which store?\"=\"Postgres\""
is "…names its source" "$(grep -c 'source claude' "$TMP/err")" "1"
runf --full
is "--full keeps the whole turn, newlines escaped" "$(printf '%s\n' "$OUT" | sed -n 2p)" '09:03	No, retry once, not three times.\nThe processor bills each attempt.'
mkdir -p "$CLAUDE_CONFIG_DIR/projects/-elsewhere"
printf '%s\n' '{"type":"user","timestamp":"2026-01-12T10:00:00.000Z","message":{"role":"user","content":"from the id"}}' >"$CLAUDE_CONFIG_DIR/projects/-elsewhere/abc-123.jsonl"
run CLAUDE_CODE_SESSION_ID=abc-123
is "claude: the session id picks the transcript" "$OUT" "10:00	from the id"

# ── Codex ────────────────────────────────────────────────────────────────
mkdir -p "$CODEX_HOME/sessions/2026/01/12"
cat >"$CODEX_HOME/sessions/2026/01/12/rollout-a.jsonl" <<JSONL
{"timestamp":"2026-01-12T11:00:00.000Z","type":"session_meta","payload":{"id":"x","cwd":"$W"}}
{"timestamp":"2026-01-12T11:00:01.000Z","type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"# AGENTS.md instructions\n\n<INSTRUCTIONS>rules</INSTRUCTIONS>"}]}}
{"timestamp":"2026-01-12T11:00:02.000Z","type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"Ship the sync engine."}]}}
{"timestamp":"2026-01-12T11:00:02.000Z","type":"event_msg","payload":{"type":"user_message","message":"Ship the sync engine."}}
{"timestamp":"2026-01-12T11:05:00.000Z","type":"event_msg","payload":{"type":"item_completed","item":{"type":"UserMessage","content":[{"type":"text","text":"That is the wrong table."}]}}}
JSONL
cat >"$CODEX_HOME/sessions/2026/01/12/rollout-b.jsonl" <<'JSONL'
{"timestamp":"2026-01-12T12:00:00.000Z","type":"session_meta","payload":{"id":"y","cwd":"/some/other/repo"}}
{"timestamp":"2026-01-12T12:00:02.000Z","type":"event_msg","payload":{"type":"user_message","message":"not this session"}}
JSONL
run
is "codex beats a claude transcript found only by directory" "$OUT" "11:00	Ship the sync engine.
11:05	That is the wrong table."
runf --source claude
is "--source claude forces the other record" "$(printf '%s\n' "$OUT" | head -n 1)" "09:00	Add a retry to checkout."
run CLAUDE_CODE_SESSION_ID=abc-123
is "…but a Claude session id wins over codex" "$OUT" "10:00	from the id"
sleep 1
cat >"$CODEX_HOME/sessions/2026/01/12/rollout-c.jsonl" <<JSONL
{"timestamp":"2026-01-12T13:00:00.000Z","type":"session_meta","payload":{"id":"z","cwd":"$W"}}
{"timestamp":"2026-01-12T13:00:01.000Z","type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"<environment_context>cwd</environment_context>"}]}}
{"timestamp":"2026-01-12T13:00:02.000Z","type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"Older format, no events."}]}}
JSONL
run
is "codex: the newest matching rollout, older format read from response items" "$OUT" "13:00	Older format, no events."
run CODEX_THREAD_ID=x
is "codex: the session's own id picks its rollout over a newer one in the same tree" "$OUT" "11:00	Ship the sync engine.
11:05	That is the wrong table."
run CODEX_THREAD_ID=no-such-session
is "codex: an id with no record fails, rather than reading another session's" "$RC" "2"
is "…printing nothing" "$OUT" ""
run CLAUDE_CODE_SESSION_ID=no-such-session
is "claude: an id with no record fails, rather than reading the newest transcript" "$RC" "2"
is "…printing nothing" "$OUT" ""

# ── corrections.sh hands a session T3 does not know to this script ───────
OUT="$(cd "$W" && bash "$HERE/corrections.sh" 2>/dev/null)"
is "corrections.sh outside T3 reads the harness transcript" "$OUT" "13:00	Older format, no events."
OUT="$(cd "$W" && bash "$HERE/corrections.sh" --full 2>/dev/null)"
is "…and passes --full through" "$OUT" "13:00	Older format, no events."

OUT="$(cd "$W" && bash "$SUT" --source nope 2>&1)"; RC=$?
is "a bad source: usage" "$RC" "2"

echo "transcripts.test.sh: $pass passed, $fail failed"
[[ $fail -eq 0 ]]
