#!/usr/bin/env -S npx tsx
// Generates integrations/README.md from integration frontmatter
// Usage: node apps/integration-index/generate.ts [--out /path/to/output.md]

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";
import process from "node:process";
import { parseFrontmatter } from "../shared/parse_frontmatter.ts";
import { validateOutcome } from "../shared/validate_outcome.ts";

// ── Types ────────────────────────────────────────────────────────────

interface IntegrationMeta {
  name: string;
  description: string;
  cli: string;
  dirName: string;
}

// ── Discovery ────────────────────────────────────────────────────────

const SKIP_DIRS = new Set(["_config", ".git"]);

function discoverIntegrations(integrationsDir: string): IntegrationMeta[] {
  const integrations: IntegrationMeta[] = [];
  const warnings: string[] = [];

  let entries: string[];
  try {
    entries = readdirSync(integrationsDir, { withFileTypes: true })
      .filter((d) => d.isDirectory() && !SKIP_DIRS.has(d.name))
      .map((d) => d.name);
  } catch {
    console.error(`Error: cannot read ${integrationsDir}`);
    process.exit(1);
  }

  for (const dirName of entries) {
    const readmePath = join(integrationsDir, dirName, "README.md");
    let content: string;
    try {
      content = readFileSync(readmePath, "utf-8");
    } catch {
      warnings.push(`${dirName}: no README.md`);
      continue;
    }

    const fm = parseFrontmatter(content);
    if (!fm) {
      warnings.push(`${dirName}: no frontmatter`);
      continue;
    }

    const name = fm.name;
    const description = fm.description;

    if (!name || !description) {
      const missing = [!name && "name", !description && "description"].filter(Boolean).join(", ");
      warnings.push(`${dirName}: missing ${missing}`);
      continue;
    }

    integrations.push({
      name,
      description,
      cli: fm.cli || "—",
      dirName,
    });
  }

  if (warnings.length > 0) {
    console.error(`Warnings (${warnings.length}):`);
    for (const w of warnings) console.error(`  - ${w}`);
  }

  return integrations;
}

// ── Build markdown ───────────────────────────────────────────────────

function truncate(desc: string, max = 90): string {
  if (desc.length <= max) return desc;
  const dot = desc.indexOf(". ");
  if (dot !== -1 && dot < max) return desc.slice(0, dot + 1);
  return desc.slice(0, max - 1) + "…";
}

function buildReadme(integrations: IntegrationMeta[]): string {
  const sorted = [...integrations].sort((a, b) => a.dirName.localeCompare(b.dirName));

  const rows = sorted.map((i) => {
    const link = `[${i.name}](${i.dirName}/)`;
    const purpose = truncate(i.description);
    return `| ${link} | ${i.cli} | ${purpose} |`;
  });

  return [
    "# Integrations",
    "",
    "External tools and services configured for use with Claude Code.",
    "",
    "<!-- Generated by apps/integration-index/generate.ts — do not edit manually -->",
    "",
    "| Integration | CLI | Use For |",
    "|-------------|-----|---------|",
    ...rows,
    "",
    `**Total: ${integrations.length} integrations**`,
    "",
    "See [CLAUDE.md](../.claude/CLAUDE.md) for repo conventions. See each integration's README for configuration details.",
    "",
  ].join("\n");
}

// ── Main ─────────────────────────────────────────────────────────────

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = join(__dirname, "../..");
const integrationsDir = join(repoRoot, "integrations");

// `--out <path>` requires a non-empty value when the flag is present — a silent
// fallback to the canonical path on a missing/empty value would let a caller
// bug overwrite the live index. `--out -` writes to stdout.
const outFlag = process.argv.indexOf("--out");
let outputPath: string;
if (outFlag === -1) {
  outputPath = join(integrationsDir, "README.md");
} else {
  const v = process.argv[outFlag + 1];
  if (!v) {
    console.error("--out flag requires a path");
    process.exit(1);
  }
  outputPath = v;
}

const integrations = discoverIntegrations(integrationsDir);
const readme = buildReadme(integrations);

if (outputPath === "-") {
  process.stdout.write(readme);
} else {
  writeFileSync(outputPath, readme, "utf-8");
}

// An empty integrations/ dir is valid (the template ships empty): the header
// always renders, so readme.length > 0 holds even with zero integrations.
validateOutcome("generate_integration_index", [
  { check: "README content generated", pass: () => readme.length > 0 },
]);

console.log(`Generated integrations/README.md: ${integrations.length} integrations`);
