#!/usr/bin/env bash
# Contextium v4 installer.
#
# Lays the Contextium AI layer into a target project so Claude Code can drive the
# Think / Do / Wrap loop from the first session. The layer's source lives in this
# repo under templates/claude/ (a normal, non-dotted folder); the installer
# materializes it as a real .claude/ in YOUR project, with CLAUDE.md inside it.
#
# Usage:
#   bash install.sh [TARGET_DIR] [--force] [--name "Your Name"]
#                   [--autonomy ask|autonomous]
#                   [--integrations "github todoist ..." | --no-integrations]
#                   [--yes]
#
#   TARGET_DIR   where to install (default: prompted, falls back to current dir)
#   --force      back up and replace a customized CLAUDE.md (CLAUDE.md.bak)
#   --name       skip the name prompt
#   --autonomy   skip the autonomy prompt
#   --integrations  copy these integration starters (space-separated names)
#   --no-integrations  start with an empty integrations/ (README stub only)
#   --yes        non-interactive: accept all defaults, never prompt
#
# Idempotent and safe to re-run: it refreshes the .claude/ layer and never
# clobbers your data dirs or a customized CLAUDE.md (unless --force).
#
# bash 3.2 compatible (macOS default). No bash 4+ features.

set -euo pipefail

# --- Constants ---

VERSION="v4.0.1"

# Tools the installer can lay down. Claude Code gets the full native .claude/
# layer; every other tool gets its native config generated by the projector
# (scripts/projector/project-rules.sh) from the one portable source.
SUPPORTED_TOOLS="claude gemini codex cursor copilot"

# This repo (the clone). The layer source is templates/claude/; integration
# starters are templates/integrations/. Resolved relative to this script.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"

# Items of the AI layer, copied from templates/claude/<item> INTO the target's
# .claude/<item> on every run (whole-path refresh). CLAUDE.md is handled
# separately (protected unless --force).
LAYER_ITEMS="rules skills agents hooks templates settings.json"

# Tool-agnostic template-owned paths refreshed on every run regardless of which
# tools are chosen. The git hooks carry their own checks under .githooks/checks/,
# so the "enforcement travels with the repo" guarantee holds for every tool —
# including the ones that never get a .claude/ dir.
REFRESH_PATHS_COMMON="
.githooks
"

# Skeleton dirs laid down on a fresh install and never clobbered after. apps/ is
# yours from the first commit: the template seeds a README and nothing else, and
# the index generator (.claude/hooks/generators/) rewrites that README in place
# as you add apps. integrations/ is handled by the picker, not here.
PROTECTED_DIRS="
apps
knowledge
journal
projects
"

# --- Colors (disabled when not a TTY) ---

if [ -t 1 ]; then
  GREEN=$'\033[0;32m'; BLUE=$'\033[0;34m'; CYAN=$'\033[0;36m'
  YELLOW=$'\033[1;33m'; DIM=$'\033[2m'; BOLD=$'\033[1m'; NC=$'\033[0m'
else
  GREEN=''; BLUE=''; CYAN=''; YELLOW=''; DIM=''; BOLD=''; NC=''
fi

# --- Helpers (functions before code) ---

err() { printf '%s\n' "${YELLOW}$*${NC}" >&2; }
ok()  { printf '  %s\n' "${GREEN}+${NC} $*"; }
info() { printf '%s\n' "${BLUE}$*${NC}"; }

banner() {
  printf '\n'
  printf '%s\n' "${BLUE}+-----------------------------------------+${NC}"
  printf '%s\n' "${BLUE}|         ${CYAN}Contextium${BLUE}                      |${NC}"
  printf '%s\n' "${BLUE}|    Give your AI an operating system     |${NC}"
  printf '%s\n' "${BLUE}|              ${DIM}${VERSION}${NC}${BLUE}                     |${NC}"
  printf '%s\n' "${BLUE}+-----------------------------------------+${NC}"
  printf '\n'
}

is_tty() { [ -t 0 ]; }

# Prompt for a value with a default. Non-interactive returns the default.
# Args: $1=prompt $2=default
ask() {
  local prompt="$1" default="$2" answer=""
  if [ "$NONINTERACTIVE" = "1" ] || ! is_tty; then
    printf '%s\n' "$default"
    return 0
  fi
  printf '%s' "${BOLD}${prompt}${NC} ${DIM}[${default}]${NC} " >&2
  IFS= read -r answer || answer=""
  if [ -z "$answer" ]; then
    printf '%s\n' "$default"
  else
    printf '%s\n' "$answer"
  fi
}

# Ask the autonomy preference. Echoes "ask" or "autonomous".
choose_autonomy() {
  local default="$1" answer=""
  if [ "$NONINTERACTIVE" = "1" ] || ! is_tty; then
    printf '%s\n' "$default"
    return 0
  fi
  printf '%s\n' "${BOLD}How should your AI operate?${NC}" >&2
  printf '%s\n' "  ${CYAN}1${NC}) ask        ${DIM}ask before host/infra changes (recommended)${NC}" >&2
  printf '%s\n' "  ${CYAN}2${NC}) autonomous ${DIM}act and report, only ask when stuck${NC}" >&2
  printf '%s' "${DIM}Choose 1 or 2${NC} ${DIM}[1]${NC} " >&2
  IFS= read -r answer || answer=""
  case "$answer" in
    2) printf '%s\n' "autonomous" ;;
    *) printf '%s\n' "ask" ;;
  esac
}

# Yes/no prompt. Non-interactive returns the default. Args: $1=prompt $2=default(y|n)
ask_yesno() {
  local prompt="$1" default="$2" answer=""
  if [ "$NONINTERACTIVE" = "1" ] || ! is_tty; then
    printf '%s\n' "$default"
    return 0
  fi
  printf '%s' "${BOLD}${prompt}${NC} ${DIM}[${default}]${NC} " >&2
  IFS= read -r answer || answer=""
  case "$answer" in
    [Yy]*) printf 'y\n' ;;
    [Nn]*) printf 'n\n' ;;
    *) printf '%s\n' "$default" ;;
  esac
}

# Copy a same-relative-path item from the template into the target, replacing any
# prior copy. Args: $1=relpath
refresh_path() {
  local rel="$1" src="$SCRIPT_DIR/$1" dst="$TARGET/$1"
  [ -e "$src" ] || return 0
  if [ -d "$src" ]; then
    rm -rf "$dst"; mkdir -p "$(dirname "$dst")"; cp -R "$src" "$dst"
  else
    mkdir -p "$(dirname "$dst")"; cp "$src" "$dst"
  fi
  ok "refreshed ${rel}"
}

# Copy from an explicit source into an explicit destination (paths differ).
# Args: $1=src-abs $2=dst-abs $3=label
copy_into() {
  local src="$1" dst="$2" label="$3"
  [ -e "$src" ] || return 0
  if [ -d "$src" ]; then
    rm -rf "$dst"; mkdir -p "$(dirname "$dst")"; cp -R "$src" "$dst"
  else
    mkdir -p "$(dirname "$dst")"; cp "$src" "$dst"
  fi
  ok "refreshed ${label}"
}

# Lay down a skeleton dir only if absent (never clobber user data). Prefers the
# template's own skeleton README when one exists, so apps/ arrives with the shape
# the index generator expects and knowledge/journal/projects arrive with the
# guidance the docs assume.
# Args: $1=relpath
seed_dir() {
  local rel="$1" dst="$TARGET/$1" skel="$SCRIPT_DIR/$1/README.md"
  if [ -e "$dst" ]; then
    ok "kept ${rel}/ (your data, untouched)"
    return 0
  fi
  mkdir -p "$dst"
  if [ -f "$skel" ]; then
    cp "$skel" "$dst/README.md"
    # The apps/ skeleton carries a "generated by the index generator" banner. That
    # generator ships inside the Claude layer, so on a non-Claude install the
    # banner names a file the user will never have. Drop it rather than point at
    # a ghost; their apps/README.md is simply a file they maintain.
    if [ "$rel" = "apps" ] && ! tool_selected claude "$SELECTED_TOOLS"; then
      grep -v 'Generated by .claude/hooks/generators/' "$dst/README.md" > "$dst/README.md.tmp" &&
        mv "$dst/README.md.tmp" "$dst/README.md"
    fi
  else
    cat > "$dst/README.md" <<EOF
# ${rel}

Starter directory. See the Contextium docs for how this fits the loop.
EOF
  fi
  ok "created ${rel}/"
}

# Up to v3.4.0 the template shipped its own machinery INTO the user's apps/:
# three index generators, a quality/ folder, and a shared/ folder of helpers.
# That machinery now lives with its callers (.claude/hooks/generators/ and
# .githooks/checks/), so on an upgrade those folders are dead weight pointing at
# a layout that no longer exists.
#
# Remove them, but only when untouched. The old apps/quality/README invited
# people to add their own checks there, so a folder holding anything beyond the
# files we shipped is now the user's — leave it alone and say so.
migrate_legacy_layout() {
  local dir known kept=0
  for dir in app-index project-index integration-index quality shared; do
    [ -d "$TARGET/apps/$dir" ] || continue
    case "$dir" in
      app-index|project-index|integration-index) known="README.md generate.ts generate.test.ts" ;;
      quality) known="README.md check-commit-subject.sh check-secrets.sh" ;;
      shared) known="README.md parse_frontmatter.ts validate_outcome.ts app_categories.json" ;;
    esac
    local extra="" f base
    for f in "$TARGET/apps/$dir"/* "$TARGET/apps/$dir"/.[!.]*; do
      [ -e "$f" ] || continue
      base="$(basename "$f")"
      case " $known " in *" $base "*) ;; *) extra="$extra $base" ;; esac
    done
    if [ -n "$extra" ]; then
      err "kept apps/${dir}/ — it holds files you added:${extra}"
      err "  The template's copies moved to .claude/hooks/ and .githooks/checks/."
      kept=1
    else
      rm -rf "$TARGET/apps/$dir"
      ok "removed apps/${dir}/ (template machinery, now shipped inside the AI layer)"
    fi
  done
  [ "$kept" = "1" ] && err "  Move what you want to keep, then delete the leftovers."

  # apps/README.md is a generated index, and the pre-v4 one lists the five
  # folders we just deleted — including a `node apps/<name>/generate.ts` command
  # that no longer resolves. It is the first file someone opens in apps/, so
  # leaving it stale hands an upgrading user a README that lies. Rebuild it:
  # regenerate from their actual apps when a generator is on hand, else lay down
  # the skeleton (and say so if their app list can't be rebuilt without one).
  local readme="$TARGET/apps/README.md"
  local gen="$TARGET/.claude/hooks/generators/app-index.generate.ts"
  if [ ! -f "$readme" ]; then
    cp "$SCRIPT_DIR/apps/README.md" "$readme"
    if ! tool_selected claude "$SELECTED_TOOLS"; then
      grep -v 'Generated by .claude/hooks/generators/' "$readme" > "$readme.tmp" &&
        mv "$readme.tmp" "$readme"
    fi
    ok "created apps/README.md"
  elif grep -qE 'app-index/|apps/<name>/generate\.ts|Generated by apps/' "$readme" 2>/dev/null; then
    if [ -f "$gen" ] && command -v node >/dev/null 2>&1 &&
       (cd "$TARGET" && node "$gen" >/dev/null 2>&1); then
      ok "rebuilt apps/README.md from your apps"
    else
      cp "$SCRIPT_DIR/apps/README.md" "$readme"
      ok "reset apps/README.md (it described the old layout)"
      if [ -n "$(find "$TARGET/apps" -mindepth 1 -maxdepth 1 -type d 2>/dev/null)" ]; then
        err "  Your apps are still there, but the index now reads empty."
        err "  Regenerate it with: node .claude/hooks/generators/app-index.generate.ts"
      fi
    fi
  fi
  return 0
}

# Materialize the AI layer: templates/claude/<item> -> TARGET/.claude/<item>.
install_ai_layer() {
  local item
  mkdir -p "$TARGET/.claude"
  for item in $LAYER_ITEMS; do
    copy_into "$SCRIPT_DIR/templates/claude/$item" "$TARGET/.claude/$item" ".claude/$item"
  done
}

# Write the starter CLAUDE.md into TARGET/.claude/CLAUDE.md, substituting the
# name + autonomy placeholders. Protected (kept) unless --force.
# Args: $1=name $2=autonomy
install_claude_md() {
  local name="$1" autonomy="$2"
  local src="$SCRIPT_DIR/templates/claude/CLAUDE.md" dst="$TARGET/.claude/CLAUDE.md"
  local autonomy_line

  if [ "$autonomy" = "autonomous" ]; then
    autonomy_line="Act and report on routine work; only stop to ask when genuinely stuck."
  else
    autonomy_line="Ask before host or infrastructure changes; diagnose and propose freely, but get a yes before mutating shared infra."
  fi

  if [ -f "$dst" ]; then
    if [ "$FORCE" = "1" ]; then
      cp "$dst" "$dst.bak"
      ok "backed up existing .claude/CLAUDE.md -> CLAUDE.md.bak"
    else
      ok "kept your .claude/CLAUDE.md (use --force to replace)"
      return 0
    fi
  fi

  mkdir -p "$TARGET/.claude"
  if [ -f "$src" ]; then
    sed -e "s/{{NAME}}/$name/g" \
        -e "s/{{AUTONOMY}}/$autonomy_line/g" \
        "$src" > "$dst"
    ok "installed .claude/CLAUDE.md (personalized for ${name})"
  else
    cat > "$dst" <<EOF
# CLAUDE.md

Working surface for ${name}. Read this first each session; the methodology
lives in \`.claude/rules/\` and the loop skills in \`.claude/skills/\`.

## The Loop

| Verb | Skill | Use when |
|---|---|---|
| Think | \`/project\` -> \`/spec\` | starting or routing a piece of work |
| Do | \`/implement\` | executing an approved SPEC in fresh context |
| Wrap | \`/close\` | journaling, committing, pushing at session end |

## Operating preference

${autonomy_line}
EOF
    ok "installed .claude/CLAUDE.md (starter, personalized for ${name})"
  fi
}

# Human-readable label for a tool key (used in the picker + summary).
tool_label() {
  case "$1" in
    claude)  echo "Claude Code     .claude/ — skills, agents, hooks (full layer)" ;;
    gemini)  echo "Gemini CLI      GEMINI.md + .gemini/commands/" ;;
    codex)   echo "Codex CLI       AGENTS.md + .codex/skills/" ;;
    cursor)  echo "Cursor          .cursor/rules/ + .cursor/commands/" ;;
    copilot) echo "GitHub Copilot  .github/copilot-instructions.md + .github/prompts/" ;;
    *)       echo "$1" ;;
  esac
}

# True if a tool key is in the selected list. Args: $1=key $2=selected-list
tool_selected() {
  case " $2 " in *" $1 "*) return 0 ;; *) return 1 ;; esac
}

# Prompt for which AI tools to set up. Echoes space-separated keys (default claude).
# Non-interactive uses ARG_TOOLS verbatim (default claude).
choose_tools() {
  if [ "$NONINTERACTIVE" = "1" ] || ! is_tty; then
    printf '%s\n' "${ARG_TOOLS:-claude}"
    return 0
  fi
  local i n m answer out=""
  printf '%s\n' "${BOLD}Which AI tools do you use?${NC} ${DIM}(space-separated, Enter for Claude Code)${NC}" >&2
  i=1
  for n in $SUPPORTED_TOOLS; do
    printf '  %s) %s\n' "${CYAN}${i}${NC}" "$(tool_label "$n")" >&2
    i=$((i + 1))
  done
  printf '%s' "${DIM}Numbers${NC} ${DIM}[1]${NC} " >&2
  IFS= read -r answer || answer=""
  [ -n "$answer" ] || { printf '%s\n' "claude"; return 0; }
  for n in $answer; do
    i=1
    for m in $SUPPORTED_TOOLS; do
      if [ "$n" = "$i" ]; then out="$out $m"; fi
      i=$((i + 1))
    done
  done
  if [ -n "$out" ]; then
    # shellcheck disable=SC2086
    printf '%s\n' $out
  else
    printf '%s\n' "claude"
  fi
}

# Validate a space-separated tool list against SUPPORTED_TOOLS; drop unknowns with
# a warning. Echoes the cleaned list (falls back to claude if nothing valid).
clean_tools() {
  local t out=""
  for t in $1; do
    if tool_selected "$t" "$SUPPORTED_TOOLS"; then
      out="$out $t"
    else
      err "Unknown tool '$t' (supported: $SUPPORTED_TOOLS) — skipping."
    fi
  done
  # shellcheck disable=SC2086
  [ -n "$out" ] && printf '%s\n' $out || printf '%s\n' "claude"
}

# Generate a non-Claude tool's native config into TARGET via the projector.
# Args: $1=tool-key
install_tool_projection() {
  bash "$SCRIPT_DIR/scripts/projector/project-rules.sh" "$1" "$TARGET" \
    | sed "s/^\[projector\] wrote /  ${GREEN}+${NC} /;/^\[projector\] done/d"
}

# List available integration starters (one name per line).
list_integrations() {
  local d
  for d in "$SCRIPT_DIR"/templates/integrations/*/; do
    [ -d "$d" ] || continue
    basename "$d"
  done
}

# Prompt for which integration starters to install. Echoes space-separated names
# (empty = none). Non-interactive uses ARG_INTEGRATIONS verbatim.
choose_integrations() {
  if [ "$NONINTERACTIVE" = "1" ] || ! is_tty; then
    printf '%s\n' "$ARG_INTEGRATIONS"
    return 0
  fi
  local names i n answer out=""
  names=$(list_integrations)
  [ -n "$names" ] || { printf '%s\n' ""; return 0; }
  printf '%s\n' "${BOLD}Which integration starters do you want?${NC} ${DIM}(Enter for none)${NC}" >&2
  i=1
  for n in $names; do
    printf '  %s) %s\n' "${CYAN}${i}${NC}" "$n" >&2
    i=$((i + 1))
  done
  printf '%s' "${DIM}Numbers, space-separated${NC} " >&2
  IFS= read -r answer || answer=""
  for n in $answer; do
    i=1
    local m
    for m in $names; do
      if [ "$n" = "$i" ]; then out="$out $m"; fi
      i=$((i + 1))
    done
  done
  # shellcheck disable=SC2086
  printf '%s\n' $out
}

# Copy the selected integration starters into TARGET/integrations/. Always leaves
# integrations/ present; if it ends up empty, drop a README stub.
install_integrations() {
  local selected="$1" name src dst
  mkdir -p "$TARGET/integrations"
  for name in $selected; do
    src="$SCRIPT_DIR/templates/integrations/$name"
    [ -d "$src" ] || { err "no such integration starter: $name"; continue; }
    dst="$TARGET/integrations/$name"
    if [ -e "$dst" ]; then
      ok "kept integrations/${name} (yours, untouched)"
    else
      cp -R "$src" "$dst"
      ok "added integrations/${name}"
    fi
  done
  if [ -z "$(ls -A "$TARGET/integrations" 2>/dev/null)" ]; then
    cat > "$TARGET/integrations/README.md" <<EOF
# integrations

External service connectors. Add one folder per product you wrap (README with
\`hosts:\` + the typed client). Starter examples ship in the Contextium repo under
\`templates/integrations/\` — re-run install.sh to pull any in.
EOF
    ok "created integrations/ (empty starter)"
  fi
}

# Turn on the tool-agnostic git hooks by pointing core.hooksPath at .githooks/.
wire_git_hooks() {
  if [ ! -d "$TARGET/.git" ]; then
    info "Not a git repo yet — skipping hooks. After 'git init', run: git -C \"$TARGET\" config core.hooksPath .githooks"
    return 0
  fi
  if [ -d "$TARGET/.githooks" ]; then
    chmod +x "$TARGET/.githooks/"* 2>/dev/null || true
    git -C "$TARGET" config core.hooksPath .githooks
    ok "wired git hooks (core.hooksPath=.githooks): commit-subject + secret scan"
  fi
}

usage() {
  cat <<EOF
Usage: bash install.sh [TARGET_DIR] [options]

  TARGET_DIR            install location (default: prompted, else current dir)

Options:
  --tools "claude gemini ..."   set up these AI tools without prompting
                                (supported: claude gemini codex cursor copilot)
  --all-tools             set up every supported tool
  --force                 replace a customized CLAUDE.md (backs up to .bak first)
  --name "Your Name"      set the name without prompting
  --autonomy ask|autonomous   set autonomy without prompting
  --integrations "a b c"  install these integration starters without prompting
  --no-integrations       start with an empty integrations/ (README stub only)
  --hooks / --no-hooks    wire (or skip) the git hooks without prompting
  --yes                   non-interactive; accept defaults, never prompt
  -h, --help              show this help

Default tool is Claude Code. Other tools get native config (GEMINI.md, AGENTS.md,
.cursor/, .github/) generated from one portable source, so the methodology never
drifts between them. Re-running refreshes config + template apps and never
clobbers your data dirs or your own apps.
EOF
}

# --- Arg parsing ---

# Keep the untouched argv. The parse loop below shifts it away, and the bootstrap
# path (script piped in on its own, no repo around it) has to hand the SAME args
# to the fetched copy — otherwise a `curl ... | bash -s -- ~/myproject` silently
# installs into the current directory instead.
ORIG_ARGS=("$@")

TARGET=""
FORCE="0"
NONINTERACTIVE="0"
ARG_NAME=""
ARG_AUTONOMY=""
ARG_INTEGRATIONS=""
ARG_HOOKS=""
ARG_TOOLS=""

while [ $# -gt 0 ]; do
  case "$1" in
    --force) FORCE="1"; shift ;;
    --yes|-y) NONINTERACTIVE="1"; shift ;;
    --name) ARG_NAME="${2:-}"; shift 2 ;;
    --autonomy) ARG_AUTONOMY="${2:-}"; shift 2 ;;
    --tools) ARG_TOOLS="${2:-}"; shift 2 ;;
    --all-tools) ARG_TOOLS="$SUPPORTED_TOOLS"; shift ;;
    --integrations) ARG_INTEGRATIONS="${2:-}"; shift 2 ;;
    --no-integrations) ARG_INTEGRATIONS=""; shift ;;
    --hooks) ARG_HOOKS="y"; shift ;;
    --no-hooks) ARG_HOOKS="n"; shift ;;
    -h|--help) usage; exit 0 ;;
    -*) err "Unknown option: $1"; usage >&2; exit 1 ;;
    *) TARGET="$1"; shift ;;
  esac
done

# --- Main ---

banner

# The layer payload has to sit next to this script. It doesn't when the script
# arrives on its own — which is exactly what `curl -sSL contextium.ai/install |
# bash` does, and that is the install command on the front page. Fetch the repo
# and hand off to the real copy rather than telling the user to go clone it.
# CONTEXTIUM_BOOTSTRAPPED guards against a clone that somehow still lacks the
# payload re-entering this branch forever.
if [ ! -d "$SCRIPT_DIR/templates/claude" ]; then
  if [ "${CONTEXTIUM_BOOTSTRAPPED:-0}" = "1" ]; then
    err "Fetched the template but templates/claude/ is missing from it."
    err "Please open an issue: https://github.com/Ashkaan/contextium/issues"
    exit 1
  fi
  command -v git >/dev/null 2>&1 || {
    err "git is required to install Contextium. Install git and re-run."
    exit 1
  }
  info "Fetching the Contextium template..."
  BOOTSTRAP_DIR="$(mktemp -d)"
  if ! git clone --quiet --depth 1 https://github.com/Ashkaan/contextium.git \
       "$BOOTSTRAP_DIR/contextium" 2>/dev/null; then
    rm -rf "$BOOTSTRAP_DIR"
    err "Could not clone https://github.com/Ashkaan/contextium.git"
    exit 1
  fi
  ok "fetched the template"
  # Run rather than exec, so the clone gets cleaned up afterwards. The child's
  # exit code is this script's exit code.
  export CONTEXTIUM_BOOTSTRAPPED=1
  set +e
  bash "$BOOTSTRAP_DIR/contextium/install.sh" ${ORIG_ARGS[@]+"${ORIG_ARGS[@]}"}
  bootstrap_rc=$?
  set -e
  rm -rf "$BOOTSTRAP_DIR"
  exit "$bootstrap_rc"
fi

# Resolve target directory.
DEFAULT_TARGET="$PWD"
if [ -z "$TARGET" ]; then
  TARGET="$(ask 'Install Contextium into which directory?' "$DEFAULT_TARGET")"
fi
if [ "$TARGET" = "~" ]; then
  TARGET="$HOME"
elif [ "${TARGET#"~/"}" != "$TARGET" ]; then
  TARGET="$HOME/${TARGET#"~/"}"
fi
mkdir -p "$TARGET"
TARGET="$(cd "$TARGET" && pwd)"

# Refuse to install into the template clone itself.
if [ "$TARGET" = "$SCRIPT_DIR" ]; then
  err "Target is the template itself. Choose a different project directory."
  exit 1
fi

# Detect fresh vs re-run (any tool's config marks an existing install).
if [ -d "$TARGET/.claude" ] || [ -f "$TARGET/GEMINI.md" ] || [ -f "$TARGET/AGENTS.md" ] \
   || [ -d "$TARGET/.cursor" ] || [ -f "$TARGET/.github/copilot-instructions.md" ]; then
  MODE="refresh"
  info "Existing Contextium config found in ${TARGET} — refreshing."
else
  MODE="fresh"
  info "Fresh install into ${TARGET}."
fi
printf '\n'

# Gather minimal profile.
NAME="$ARG_NAME"
if [ -z "$NAME" ]; then
  NAME="$(ask "What's your name?" "${USER:-developer}")"
fi

AUTONOMY="$ARG_AUTONOMY"
case "$AUTONOMY" in
  ask|autonomous) : ;;
  "") AUTONOMY="$(choose_autonomy ask)" ;;
  *) err "Invalid --autonomy '$AUTONOMY' (use ask|autonomous); defaulting to ask."; AUTONOMY="ask" ;;
esac
printf '\n'

# Which AI tools to set up.
if [ -n "$ARG_TOOLS" ]; then
  SELECTED_TOOLS="$(clean_tools "$ARG_TOOLS")"
else
  SELECTED_TOOLS="$(clean_tools "$(choose_tools)")"
fi
printf '\n'
info "Setting up:${SELECTED_TOOLS}"

# Claude Code gets the full native layer; non-Claude tools get projected config.
if tool_selected claude "$SELECTED_TOOLS"; then
  info "Installing the Claude Code layer (.claude/)..."
  install_ai_layer
  install_claude_md "$NAME" "$AUTONOMY"
fi

for tool in $SELECTED_TOOLS; do
  if [ "$tool" != "claude" ]; then
    info "Generating $(printf '%s' "$tool") config..."
    install_tool_projection "$tool"
  fi
done

# Tool-agnostic enforcement (the git hooks, which carry their own checks) — always.
for rel in $REFRESH_PATHS_COMMON; do
  refresh_path "$rel"
done

# Seed protected data dirs (only when absent).
for rel in $PROTECTED_DIRS; do
  seed_dir "$rel"
done

# Upgrades from <= v3.4.0: take our machinery back out of the user's apps/.
migrate_legacy_layout

# Integration starters: pick, then copy the selected ones.
SELECTED_INTEGRATIONS="$(choose_integrations)"
install_integrations "$SELECTED_INTEGRATIONS"
printf '\n'

# Wire the tool-agnostic git hooks (commit-subject + secret scan).
HOOKS="$ARG_HOOKS"
if [ -z "$HOOKS" ]; then
  HOOKS="$(ask_yesno 'Wire git hooks so enforcement works at commit time?' y)"
fi
if [ "$HOOKS" = "y" ]; then
  wire_git_hooks
else
  info "Skipped git hooks. Turn them on later: git config core.hooksPath .githooks"
fi
printf '\n'

# --- Next steps ---

printf '%s\n' "${GREEN}=========================================${NC}"
printf '%s\n' "${GREEN}  Contextium ${VERSION} ready in ${TARGET}${NC}"
printf '%s\n' "${GREEN}=========================================${NC}"
printf '\n'

if [ "$MODE" = "refresh" ]; then
  printf '%s\n' "Refreshed the config for:${SELECTED_TOOLS}. Your data dirs were left as-is."
  printf '\n'
fi
printf '%s\n' "You're set up for:${SELECTED_TOOLS}"
printf '%s\n' "Open this repo in your tool and run the Loop — same Think / Do / Wrap everywhere:"
for tool in $SELECTED_TOOLS; do
  case "$tool" in
    claude)  printf '%s\n' "  - ${BOLD}Claude Code${NC}: ${BOLD}cd ${TARGET} && claude${NC}, then ${BOLD}/project${NC}. Read ${BOLD}.claude/CLAUDE.md${NC}." ;;
    gemini)  printf '%s\n' "  - ${BOLD}Gemini CLI${NC}: reads ${BOLD}GEMINI.md${NC}; run ${BOLD}/project${NC} from ${BOLD}.gemini/commands/${NC}." ;;
    codex)   printf '%s\n' "  - ${BOLD}Codex${NC}: reads ${BOLD}AGENTS.md${NC}; the Loop skills are in ${BOLD}.codex/skills/${NC}." ;;
    cursor)  printf '%s\n' "  - ${BOLD}Cursor${NC}: rules in ${BOLD}.cursor/rules/${NC}; run ${BOLD}/project${NC} from ${BOLD}.cursor/commands/${NC}." ;;
    copilot) printf '%s\n' "  - ${BOLD}Copilot${NC}: reads ${BOLD}.github/copilot-instructions.md${NC}; prompts in ${BOLD}.github/prompts/${NC}." ;;
  esac
done
printf '\n'
printf '%s\n' "The methodology and rules are identical across tools. Git-hook enforcement is on"
printf '%s\n' "for all of them; fresh-context review agents are a Claude Code bonus."
printf '\n'
