// Boundary rows for the generators: the repo root they resolve in both
// layouts, the frontmatter values a project README now carries, and the
// project index against a fixture repo — empty, one project, the preamble kept.
// Run: node --test .agents/generators/generators.test.ts

import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { chmodSync, cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { parseFrontmatter } from "./parse_frontmatter.ts";
import { repoRoot } from "./repo_root.ts";

const here = dirname(fileURLToPath(import.meta.url));

test("repoRoot: installed layout is two levels up", () => {
  const url = pathToFileURL("/r/.agents/generators/x.generate.ts").href;
  assert.equal(repoRoot(url), "/r");
});

test("repoRoot: authoring layout is three levels up", () => {
  const url = pathToFileURL("/r/templates/agents/generators/x.generate.ts").href;
  assert.equal(repoRoot(url), "/r");
});

test("parseFrontmatter: a quoted next: keeps its colon", () => {
  const fm = parseFrontmatter('---\nnext: "R3: checkout retries"\n---\n');
  assert.equal(fm?.next, "R3: checkout retries");
});

test("parseFrontmatter: a trailing comment is not part of the value", () => {
  const fm = parseFrontmatter("---\npriority: high   # required on active\ndescription: the #1 tool\n---\n");
  assert.equal(fm?.priority, "high");
  assert.equal(fm?.description, "the");
});

test("parseFrontmatter: a missing next: is undefined, not empty", () => {
  const fm = parseFrontmatter("---\nstatus: blocked\nblocked-on: vendor reply\n---\n\n## Goal\n\nx\n");
  assert.equal(fm?.next, undefined);
  assert.equal(fm?.["blocked-on"], "vendor reply");
});

// A throwaway installed repo: .agents/generators copied in, projects/ as given.
function fixture(projects: Record<string, string>, readme?: string): string {
  const repo = mkdtempSync(join(tmpdir(), "ctx-gen-"));
  cpSync(here, join(repo, ".agents", "generators"), { recursive: true });
  mkdirSync(join(repo, "projects"), { recursive: true });
  for (const [path, body] of Object.entries(projects)) {
    mkdirSync(join(repo, "projects", dirname(path)), { recursive: true });
    writeFileSync(join(repo, "projects", path), body);
  }
  if (readme !== undefined) writeFileSync(join(repo, "projects", "README.md"), readme);
  return repo;
}

function run(repo: string, ...args: string[]): string {
  return execFileSync(process.execPath, [join(repo, ".agents/generators/project-index.generate.ts"), ...args], {
    cwd: repo,
    encoding: "utf-8",
    stdio: ["ignore", "pipe", "pipe"],
  });
}

const PROJECT = `---
project: checkout-flow
status: active
priority: high
created: 2026-01-10
description: Card checkout that survives a declined card
next: "R2: retry on declined cards"
---

# Project: Checkout flow

## Goal

Checkout keeps the order when a card is declined.

## Outcome

`;

test("project index: zero projects still renders the header", (t) => {
  const repo = fixture({});
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  const out = run(repo, "--out", "-");
  assert.match(out, /^# Active Project Status Overview/);
  assert.match(out, /\*None\*/);
});

test("project index: one project shows its derived next:", (t) => {
  const repo = fixture({ "web/2026-01-10_checkout-flow/README.md": PROJECT });
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  const out = run(repo, "--out", "-");
  assert.match(out, /\| Priority \| Domain \| Project \| Description \| Next \|/);
  assert.match(
    out,
    /\[checkout-flow\]\(web\/2026-01-10_checkout-flow\/README\.md\) \| Card checkout that survives a declined card \| R2: retry on declined cards \|/,
  );
});

test("project index: the text above the marker survives a rewrite", (t) => {
  const preamble = "# Projects\n\nMy own words.\n\n<!-- Generated by .agents/generators/project-index.generate.ts below this line — edit the text above it only -->\n";
  const repo = fixture({ "web/2026-01-10_checkout-flow/README.md": PROJECT }, `${preamble}\nstale index\n`);
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  run(repo);
  const written = readFileSync(join(repo, "projects/README.md"), "utf-8");
  assert.ok(written.startsWith(`${preamble}\n## Active Project Status Overview`), written.slice(0, 300));
  assert.doesNotMatch(written, /stale index/);
  assert.match(written, /R2: retry on declined cards/);
});

test("project index: without a marker the index is the whole file", (t) => {
  const repo = fixture({}, "# Active Project Status Overview\n\nold\n");
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  run(repo);
  const written = readFileSync(join(repo, "projects/README.md"), "utf-8");
  assert.ok(written.startsWith("# Active Project Status Overview"));
  assert.doesNotMatch(written, /\nold\n/);
});

test("project index: --out with no path is refused", (t) => {
  const repo = fixture({});
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  assert.throws(() => run(repo, "--out"), /--out flag requires a path/);
});

test("project index: a README it cannot read is an error, not an empty preamble", (t) => {
  const preamble = "# Projects\n\nMy own words.\n\n<!-- Generated by .agents/generators/project-index.generate.ts below this line -->\n";
  const repo = fixture({}, preamble);
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  // Write-only: the read fails with EACCES while a write would still succeed,
  // so treating the error as "no preamble" would overwrite the user's text.
  const readme = join(repo, "projects", "README.md");
  chmodSync(readme, 0o200);
  assert.throws(() => run(repo), /EACCES/);
  chmodSync(readme, 0o600);
  assert.equal(readFileSync(readme, "utf-8"), preamble);
});
