#!/usr/bin/env -S node --experimental-strip-types
// Prints the integration index from integration frontmatter. It does NOT write
// integrations/README.md: that README is hand-maintained and holds the
// manifest schema .agents/checks/check-integration-manifest.ts enforces, so a
// generated copy over it would delete the schema.
// Usage: node .agents/generators/integration-index.generate.ts [--out /path/to/output.md]

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import process from "node:process";
import { parseFrontmatter } from "./parse_frontmatter.ts";
import { oneLineCell } from "./table_cell.ts";
import { repoRoot } from "./repo_root.ts";
import { validateOutcome } from "./validate_outcome.ts";

// ── Types ────────────────────────────────────────────────────────────

interface IntegrationMeta {
  name: string;
  description: string;
  cli: string;
  dirName: string;
}

// ── Discovery ────────────────────────────────────────────────────────

const SKIP_DIRS = new Set(["_config", ".git"]);

function discoverIntegrations(integrationsDir: string): { integrations: IntegrationMeta[]; drops: number } {
  const integrations: IntegrationMeta[] = [];
  const warnings: string[] = [];

  let entries: string[];
  try {
    entries = readdirSync(integrationsDir, { withFileTypes: true })
      .filter((d) => d.isDirectory() && !SKIP_DIRS.has(d.name))
      .map((d) => d.name);
  } catch {
    console.error(`Error: cannot read ${integrationsDir}`);
    process.exit(1);
  }

  for (const dirName of entries) {
    const readmePath = join(integrationsDir, dirName, "README.md");
    let content: string;
    try {
      content = readFileSync(readmePath, "utf-8");
    } catch {
      warnings.push(`${dirName}: no README.md`);
      continue;
    }

    const fm = parseFrontmatter(content);
    if (!fm) {
      warnings.push(`${dirName}: no frontmatter`);
      continue;
    }

    const name = fm.name;
    const description = fm.description;

    if (!name || !description) {
      const missing = [!name && "name", !description && "description"].filter(Boolean).join(", ");
      warnings.push(`${dirName}: missing ${missing}`);
      continue;
    }

    integrations.push({
      name,
      description,
      cli: fm.cli || "—",
      dirName,
    });
  }

  if (warnings.length > 0) {
    console.error(`Warnings (${warnings.length}):`);
    for (const w of warnings) console.error(`  - ${w}`);
  }

  // Every warning is an integration left out of the index.
  return { integrations, drops: warnings.length };
}

// ── Build markdown ───────────────────────────────────────────────────

function truncate(desc: string, max = 90): string {
  if (desc.length <= max) return desc;
  const dot = desc.indexOf(". ");
  if (dot !== -1 && dot < max) return desc.slice(0, dot + 1);
  return desc.slice(0, max - 1) + "…";
}

function buildReadme(integrations: IntegrationMeta[]): string {
  const sorted = [...integrations].sort((a, b) => a.dirName.localeCompare(b.dirName));

  const rows = sorted.map((i) => {
    const link = `[${oneLineCell(i.name)}](${i.dirName}/)`;
    const purpose = oneLineCell(truncate(i.description));
    return `| ${link} | ${oneLineCell(i.cli)} | ${purpose} |`;
  });

  return [
    "# Integrations",
    "",
    "External tools and services the AI layer is configured to reach.",
    "",
    "<!-- Generated by .agents/generators/integration-index.generate.ts — do not edit manually -->",
    "",
    "| Integration | CLI | Use For |",
    "|-------------|-----|---------|",
    ...rows,
    "",
    `**Total: ${integrations.length} integrations**`,
    "",
    "See [AGENTS.md](../AGENTS.md) for repo conventions. See each integration's README for configuration details.",
    "",
  ].join("\n");
}

// ── Main ─────────────────────────────────────────────────────────────

const root = repoRoot(import.meta.url);
const integrationsDir = join(root, "integrations");

// stdout by default. `--out <path>` writes a file and requires a non-empty
// value when the flag is present. `--out -` is stdout too.
const outFlag = process.argv.indexOf("--out");
let outputPath: string;
if (outFlag === -1) {
  outputPath = "-";
} else {
  const v = process.argv[outFlag + 1];
  if (!v) {
    console.error("--out flag requires a path");
    process.exit(1);
  }
  outputPath = v;
}

const { integrations, drops } = discoverIntegrations(integrationsDir);

// A file the index replaces is refused while an integration could not be read:
// a partial index would overwrite the last good one. stdout replaces nothing.
if (outputPath !== "-" && drops > 0) {
  console.error(
    `--out ${outputPath}: refused, ${drops} integration(s) could not be read (see the warnings above); the file was left as it was`,
  );
  process.exit(1);
}

const readme = buildReadme(integrations);

if (outputPath === "-") {
  process.stdout.write(readme);
} else {
  writeFileSync(outputPath, readme, "utf-8");
}

// An empty integrations/ dir is valid (the template ships empty): the header
// always renders, so readme.length > 0 holds even with zero integrations.
validateOutcome("generate_integration_index", [{ check: "README content generated", pass: () => readme.length > 0 }]);

if (outputPath !== "-")
  console.error(`Wrote the integration index to ${outputPath}: ${integrations.length} integrations`);
