#!/usr/bin/env bash
# project-rules.sh — project the Contextium methodology into per-tool instruction
# files from ONE source, so they never drift.
#
# Source of truth:
#   .claude/templates/methodology.md   (portable, tool-agnostic working agreement)
#   .claude/rules/*.md                 (the 8 principle rules)
# Output: a single assembled body, written into each requested tool's expected
# instruction file with the right path + wrapper.
#
# Usage:
#   project-rules.sh                 # generate AGENTS.md (the cross-tool default)
#   project-rules.sh all             # generate every supported tool's file
#   project-rules.sh cursor gemini   # generate just those
#   project-rules.sh --list          # list supported tools + their target files
#
# Re-runnable: regenerates from the current source every time. Edit the rules or
# methodology.md, re-run, and every tool file updates in lockstep.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
METHODOLOGY="$REPO_ROOT/.claude/templates/methodology.md"
RULES_DIR="$REPO_ROOT/.claude/rules"

# tool key -> "relative/output/path"
tool_path() {
  case "$1" in
    agents)   echo "AGENTS.md" ;;
    cursor)   echo ".cursor/rules/contextium.mdc" ;;
    gemini)   echo "GEMINI.md" ;;
    copilot)  echo ".github/copilot-instructions.md" ;;
    windsurf) echo ".windsurfrules" ;;
    cline)    echo ".clinerules" ;;
    aider)    echo "CONVENTIONS.md" ;;
    *)        return 1 ;;
  esac
}
ALL_TOOLS="agents cursor gemini copilot windsurf cline aider"

die() { echo "FATAL: $*" >&2; exit 1; }
[[ -f "$METHODOLOGY" ]] || die "missing $METHODOLOGY"
[[ -d "$RULES_DIR" ]] || die "missing $RULES_DIR"

if [[ "${1:-}" == "--list" ]]; then
  echo "Supported tools (key -> file):"
  for t in $ALL_TOOLS; do printf '  %-9s %s\n' "$t" "$(tool_path "$t")"; done
  exit 0
fi

# ── Assemble the shared body once ──────────────────────────────────────────
build_body() {
  cat "$METHODOLOGY"
  echo
  echo "# Principles"
  echo
  echo "These are the always-on rules. A reference of the form \`@rule:\` plus a heading id below points"
  echo "at the matching principle."
  echo
  for f in "$RULES_DIR"/*.md; do
    [[ -f "$f" ]] || continue
    # Drop the file's leading H1 title line; keep the rest (the ## <id> heading + body).
    awk 'NR==1 && /^# / {next} {print}' "$f"
    echo
  done
}

BODY="$(build_body)"

GEN_NOTE="<!-- Generated by apps/projector/project-rules.sh from .claude/templates/methodology.md + .claude/rules/*.md. Do not edit by hand; edit the source and re-run. -->"

write_tool() {
  local tool="$1" rel out dir
  rel="$(tool_path "$tool")" || die "unknown tool: $tool (try --list)"
  out="$REPO_ROOT/$rel"
  dir="$(dirname "$out")"
  mkdir -p "$dir"
  case "$tool" in
    cursor)
      # Cursor reads .mdc with YAML-ish front matter; alwaysApply keeps it loaded.
      { printf -- '---\ndescription: Contextium methodology and principles\nalwaysApply: true\n---\n\n'
        printf '%s\n\n' "$GEN_NOTE"
        printf '%s\n' "$BODY"; } > "$out" ;;
    *)
      { printf '%s\n\n' "$GEN_NOTE"; printf '%s\n' "$BODY"; } > "$out" ;;
  esac
  echo "[projector] wrote $rel"
}

# ── Resolve requested tools ────────────────────────────────────────────────
requested=()
if [[ $# -eq 0 ]]; then
  requested=(agents)
elif [[ "$1" == "all" ]]; then
  # shellcheck disable=SC2206
  requested=( $ALL_TOOLS )
else
  requested=( "$@" )
fi

for t in "${requested[@]}"; do write_tool "$t"; done
echo "[projector] done (${#requested[@]} file(s))"
