#!/usr/bin/env bash
# project-rules.sh — project the Contextium methodology, rules, and Loop commands
# into a tool's native config files, from ONE source so they never drift.
#
# Claude Code is NOT handled here — the installer copies templates/claude/ into a
# real .claude/ directly. This projector covers every OTHER supported tool, whose
# config is generated from the portable source.
#
# Sources (relative to repo root):
#   templates/methodology.md      the portable working agreement
#   templates/claude/rules/*.md   the principle rules (shared with the Claude layer)
#   templates/commands/*.md       the portable Loop commands (frontmatter: name, description)
#
# Per-tool output (written into TARGET_DIR):
#   gemini   GEMINI.md                        + .gemini/commands/<name>.toml
#   codex    AGENTS.md                        + .codex/skills/<name>/SKILL.md
#   cursor   .cursor/rules/contextium.mdc     + .cursor/commands/<name>.md
#   copilot  .github/copilot-instructions.md  + .github/prompts/<name>.prompt.md
#
# Usage:
#   project-rules.sh <tool> <target_dir>   # write <tool>'s files into target_dir
#   project-rules.sh --list                # list supported tools + their targets
#
# Re-runnable: regenerates from the current source every time. Edit the source and
# re-run, and every tool's files update in lockstep. bash 3.2 compatible.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
METHODOLOGY="$REPO_ROOT/templates/methodology.md"
RULES_DIR="$REPO_ROOT/templates/claude/rules"
COMMANDS_DIR="$REPO_ROOT/templates/commands"

ALL_TOOLS="gemini codex cursor copilot"
GEN_NOTE="<!-- Generated by scripts/projector/project-rules.sh from templates/methodology.md + templates/claude/rules/*.md. Do not edit by hand; edit the source and re-run. -->"

die() { echo "FATAL: $*" >&2; exit 1; }

if [ "${1:-}" = "--list" ]; then
  echo "Supported tools (key -> instructions file + commands):"
  echo "  gemini    GEMINI.md                       + .gemini/commands/*.toml"
  echo "  codex     AGENTS.md                       + .codex/skills/*/SKILL.md"
  echo "  cursor    .cursor/rules/contextium.mdc    + .cursor/commands/*.md"
  echo "  copilot   .github/copilot-instructions.md + .github/prompts/*.prompt.md"
  exit 0
fi

TOOL="${1:-}"
TARGET="${2:-}"
[ -n "$TOOL" ] && [ -n "$TARGET" ] || die "usage: project-rules.sh <tool> <target_dir> (try --list)"
[ -f "$METHODOLOGY" ] || die "missing $METHODOLOGY"
[ -d "$RULES_DIR" ] || die "missing $RULES_DIR"
[ -d "$COMMANDS_DIR" ] || die "missing $COMMANDS_DIR"
case " $ALL_TOOLS " in *" $TOOL "*) : ;; *) die "unknown tool: $TOOL (try --list)";; esac
mkdir -p "$TARGET"

# --- Source assembly --------------------------------------------------------

# methodology + every principle rule (rule H1 titles dropped; ## id headings kept)
build_body() {
  cat "$METHODOLOGY"
  echo
  echo "# Principles"
  echo
  echo "These are the always-on rules — the same ones a Claude Code session loads from .claude/rules/."
  echo
  for f in "$RULES_DIR"/*.md; do
    [ -f "$f" ] || continue
    awk 'NR==1 && /^# / {next} {print}' "$f"
    echo
  done
}

# Read a frontmatter field (name/description) from a command source file.
cmd_field() {  # $1=file $2=field
  awk -v field="$2" '
    /^---$/ { d++; next }
    d==1 && index($0, field": ")==1 { print substr($0, length(field)+3); exit }
  ' "$1"
}

# Body of a command source file (everything after the closing ---).
cmd_body() {  # $1=file
  awk 'BEGIN{d=0} /^---$/{d++; next} d>=2{print}' "$1"
}

BODY="$(build_body)"

# --- Per-tool instructions file ---------------------------------------------

write_instructions() {
  local out dir
  case "$TOOL" in
    gemini)  out="$TARGET/GEMINI.md" ;;
    codex)   out="$TARGET/AGENTS.md" ;;
    copilot) out="$TARGET/.github/copilot-instructions.md" ;;
    cursor)  out="$TARGET/.cursor/rules/contextium.mdc" ;;
  esac
  dir="$(dirname "$out")"; mkdir -p "$dir"
  if [ "$TOOL" = "cursor" ]; then
    { printf -- '---\ndescription: Contextium methodology and principles\nalwaysApply: true\n---\n\n'
      printf '%s\n\n' "$GEN_NOTE"
      printf '%s\n' "$BODY"; } > "$out"
  else
    { printf '%s\n\n' "$GEN_NOTE"; printf '%s\n' "$BODY"; } > "$out"
  fi
  echo "[projector] wrote ${out#"$TARGET"/}"
}

# --- Per-tool command files -------------------------------------------------

write_commands() {
  local f name desc body out dir
  for f in "$COMMANDS_DIR"/*.md; do
    [ -f "$f" ] || continue
    name="$(cmd_field "$f" name)"
    desc="$(cmd_field "$f" description)"
    body="$(cmd_body "$f")"
    [ -n "$name" ] || die "command source $f missing 'name:' frontmatter"
    case "$TOOL" in
      gemini)
        dir="$TARGET/.gemini/commands"; mkdir -p "$dir"
        out="$dir/$name.toml"
        { printf 'description = "%s"\n' "$desc"
          printf 'prompt = """\n%s\n"""\n' "$body"; } > "$out" ;;
      codex)
        dir="$TARGET/.codex/skills/$name"; mkdir -p "$dir"
        out="$dir/SKILL.md"
        { printf -- '---\nname: %s\ndescription: %s\n---\n\n' "$name" "$desc"
          printf '%s\n' "$body"; } > "$out" ;;
      cursor)
        dir="$TARGET/.cursor/commands"; mkdir -p "$dir"
        out="$dir/$name.md"
        { printf '# /%s\n\n%s\n\n' "$name" "$desc"; printf '%s\n' "$body"; } > "$out" ;;
      copilot)
        dir="$TARGET/.github/prompts"; mkdir -p "$dir"
        out="$dir/$name.prompt.md"
        { printf -- '---\ndescription: %s\n---\n\n' "$desc"; printf '%s\n' "$body"; } > "$out" ;;
    esac
    echo "[projector] wrote ${out#"$TARGET"/}"
  done
}

write_instructions
write_commands
echo "[projector] done: $TOOL -> $TARGET"
